[mypy]
explicit_package_bases = true
mypy_path=src
files=localemu/aws/api/core.py,localemu/utils/files.py,localemu/utils/docker_utils.py,localemu/utils/threads.py,localemu/utils/strings.py,localemu/packages,localemu/services/transcribe,localemu/services/kinesis/packages.py
ignore_missing_imports = False
follow_imports = silent
ignore_errors = False
disallow_untyped_defs = True
disallow_untyped_calls = True
disallow_any_generics = True
disallow_subclassing_any = True
warn_unused_ignores = True

[mypy-localemu.services.lambda_.invocation.*,localemu.services.lambda_.provider]
ignore_errors = False
disallow_untyped_defs = True
disallow_untyped_calls = True
disallow_any_generics = True
allow_untyped_globals = False
