"""Real-AWS providers, variables, and tfvars file generation.

These files differ from the legacy ``aws``-target writer in three ways:

* Account id is *asserted* via ``allowed_account_ids`` so a misconfigured
  credential chain can't deploy to a different account by accident.
* Region is pinned to ``--aws-region``.
* Secret values are declared as Terraform ``variable`` blocks with
  ``sensitive = true``, never as static strings.
"""

from __future__ import annotations

from typing import Iterable

from localemu.export.realaws.secrets import SecretSlot


def build_providers_tf(target_account: str, target_region: str) -> str:
    """Return the contents of ``providers.tf`` pinned to the target account.

    The credential chain is intentionally left empty: the user supplies
    credentials at apply time via the same ``--aws-profile`` /
    ``--aws-access-key-id`` flow that the export itself used. This keeps
    secrets out of the generated source tree.
    """
    return (
        "terraform {\n"
        '  required_version = ">= 1.5"\n'
        "  required_providers {\n"
        "    aws = {\n"
        '      source  = "hashicorp/aws"\n'
        '      version = "~> 5.0"\n'
        "    }\n"
        "  }\n"
        "}\n"
        "\n"
        'provider "aws" {\n'
        f"  region              = var.aws_region\n"
        f"  allowed_account_ids = [var.aws_account_id]\n"
        "}\n"
    )


def build_variables_tf(secret_slots: Iterable[SecretSlot]) -> str:
    """Return the contents of ``variables.tf``.

    Always declares ``aws_account_id`` and ``aws_region`` (so the
    providers block can reference them). Adds one ``variable`` per
    secret slot, marked ``sensitive = true``.
    """
    parts: list[str] = [
        'variable "aws_account_id" {\n'
        '  description = "Target AWS account id (asserted by the provider)."\n'
        "  type        = string\n"
        "}\n",
        'variable "aws_region" {\n'
        '  description = "Target AWS region."\n'
        "  type        = string\n"
        "}\n",
    ]

    for slot in secret_slots:
        parts.append(
            f'variable "{slot.variable_name}" {{\n'
            f'  description = "Secret value for '
            f'{slot.service}.{slot.resource_type} {slot.resource_id} '
            f'({slot.attribute_path}). Populate via -var or '
            f'terraform.tfvars before apply."\n'
            "  type        = string\n"
            "  sensitive   = true\n"
            "}\n"
        )
    return "\n".join(parts)


def build_tfvars_example(
    target_account: str,
    target_region: str,
    secret_slots: Iterable[SecretSlot],
) -> str:
    """Return the contents of ``terraform.tfvars.example``.

    Sample secret values come from LocalEmu when known; otherwise we
    leave a placeholder string the user is expected to overwrite.
    """
    lines: list[str] = [
        "# Auto-generated by `localemu export`. Copy to terraform.tfvars and",
        "# replace any REPLACE_ME values with the secrets you want deployed.",
        "#",
        "# SAFETY: secret values are NEVER written to this file — placeholders",
        "# only. Look up each value (or use a fresh one) and substitute it into",
        "# your (gitignored) terraform.tfvars before running `terraform apply`.",
        "",
        f'aws_account_id = "{target_account}"',
        f'aws_region     = "{target_region}"',
        "",
    ]
    for slot in secret_slots:
        # Always REPLACE_ME — never echo the LocalEmu value, even if known.
        # The point of redaction is that secrets do not flow into export
        # artifacts, including the example tfvars file.
        escaped = "REPLACE_ME"
        lines.append(
            f'# {slot.service}.{slot.resource_type} {slot.resource_id} '
            f"({slot.attribute_path})"
        )
        lines.append(f'{slot.variable_name} = "{escaped}"')
        lines.append("")
    return "\n".join(lines)


def build_deploy_script() -> str:
    """Return a minimal POSIX shell script driving the deploy."""
    return (
        "#!/usr/bin/env bash\n"
        "# Deploy this LocalEmu export to real AWS.\n"
        "#\n"
        "# Prerequisites:\n"
        "#   - terraform >= 1.5\n"
        "#   - AWS credentials in env / profile / instance role\n"
        "#   - terraform.tfvars populated from terraform.tfvars.example\n"
        "set -euo pipefail\n"
        'cd "$(dirname "$0")"\n'
        "\n"
        "if [[ ! -f terraform.tfvars ]]; then\n"
        '  echo "terraform.tfvars not found; copy from terraform.tfvars.example" >&2\n'
        "  exit 2\n"
        "fi\n"
        "\n"
        "terraform init -input=false\n"
        'terraform apply -input=false -auto-approve "$@"\n'
    )
